### ISSUE TITLE
Missing gems (jgrep, json_pure) in RHS6

### ISSUE THREAD

**Issue by milanzelenka** [hjensas/bootdisk_hook#1]
Hello,

In Red Hat Satellite 6.2 (Foreman 1.11) there are missing GEM dependences: jgrep and json_pure.

This is how to install them:

```
scl enable tfm bash
gem install jgrep
gem install json_pure

```
Maybe it could be mentioned in README.

Regards,
Milan

**Comment by hjensas** [comment]
Hello,

Yes, this is correct.
I belive the dependencies can also be pulled from EPEL.
rubygem-jgrep-1.3.3-3.el7.noarch.rpm

I'll add this to the readme.

Thanks!

Regards,
Harald
